name: Keep Gofile Alive

on:
  schedule:
    - cron: "00 7 */3 * *"
  workflow_dispatch:
    inputs:
      verbose:
        description: 'Enable verbose logging'
        required: false
        default: 'false'
        type: boolean
      max_retries:
        description: 'Maximum retries per operation'
        required: false
        default: '3'
        type: string

env:
  FORCE_COLOR: 1

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: node:20-alpine
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apk add --no-cache chromium nss freetype harfbuzz ca-certificates ttf-freefont

      - name: Install Node.js dependencies
        run: npm ci --only=production --ignore-scripts

      - name: Run GoFile Keep Alive
        run: node src/ping-gofile.js
        env:
          GOFILE_URLS: ${{ secrets.GOFILE_URLS }}
          VERBOSE: ${{ github.event.inputs.verbose || 'false' }}
          MAX_RETRIES: ${{ github.event.inputs.max_retries || '3' }}
          HEADLESS: 'true'
          PAGE_TIMEOUT: '60000'
          WAIT_TIME: '5000'
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
          PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH: '/usr/bin/chromium-browser'

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-logs-${{ github.run_id }}
          path: |
            /tmp/*.log
          retention-days: 3
