name: Keep Gofile Alive

on:
  schedule:
    - cron: "00 7 */5 * *"
  workflow_dispatch:
    inputs:
      verbose:
        description: 'Enable verbose logging'
        required: false
        default: 'false'
        type: boolean
      max_retries:
        description: 'Maximum retries per operation'
        required: false
        default: '3'
        type: string

env:
  FORCE_COLOR: 1

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      matrix:
        node-version: [20]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-
            playwright-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browser
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2t64 libatk-bridge2.0-0 libdrm2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxss1 libgtk-3-0 libgdk-pixbuf2.0-0 libcairo-gobject2 libpango-1.0-0 libatk1.0-0
          npx playwright install chromium

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Run GoFile Keep Alive
        run: npm start
        env:
          GOFILE_URLS: ${{ secrets.GOFILE_URLS }}
          VERBOSE: ${{ github.event.inputs.verbose || 'false' }}
          MAX_RETRIES: ${{ github.event.inputs.max_retries || '3' }}
          HEADLESS: 'true'
          PAGE_TIMEOUT: '60000'
          WAIT_TIME: '5000'

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-logs-${{ github.run_id }}
          path: |
            /tmp/*.log
            /home/runner/.npm/_logs/
          retention-days: 7
